project_id = "lfsdqyvvboapsyeauchm"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.ws-router]
verify_jwt = false

[functions.ws-exec]
verify_jwt = false

[functions.batches-retrieve]
verify_jwt = false

[functions.batch-details]
verify_jwt = false

[functions.validate-command]
verify_jwt = false

[functions.validate-batch]
verify_jwt = false

[functions.ca-helper]
verify_jwt = false

[functions.health]
verify_jwt = false

[functions.ultaai-backend]
verify_jwt = false

[functions.classify-command]
verify_jwt = false

[functions.command-confirmations]
verify_jwt = false

[functions.cleanup-expired-confirmations]
verify_jwt = false

[functions.signer-hook]
verify_jwt = false

[functions.chat-api]
verify_jwt = false

[functions.widget-api]
verify_jwt = false

[functions.widget-admin-api]
verify_jwt = true

[functions.chat-router]
verify_jwt = false

[functions.agent-heartbeat]
verify_jwt = false

[functions.ultaai-router-payload]
verify_jwt = false

[functions.agent-control]
verify_jwt = false

[functions.agent-deploy]
verify_jwt = false

[functions.script-batches]
verify_jwt = false

[functions.ultaai-router-decide]
verify_jwt = false

[functions.ultaai-preflight-run]
verify_jwt = false

[functions.ultaai-policy-check]
verify_jwt = false

[functions.ultaai-exec-run]
verify_jwt = false

[functions.ultaai-advice]
verify_jwt = false

[functions.ultaai-command-suggest]
verify_jwt = false

[functions.console-invites]
verify_jwt = true

[functions.check-permissions]
verify_jwt = true

[functions.sendgrid-email]
verify_jwt = false

[functions.password-reset]
verify_jwt = false