-- Create console pages with comprehensive page list including dashboard sections
INSERT INTO console_pages (key, label, description, category) VALUES
  ('dashboard', 'Dashboard', 'Main dashboard view', 'core'),
  ('dashboard-revenue', 'Revenue Section', 'Revenue overview on dashboard', 'dashboard-section'),
  ('dashboard-ai-costs', 'AI Cost Monitor', 'AI cost tracking on dashboard', 'dashboard-section'),
  ('dashboard-agent-usage', 'Agent Usage Chart', 'Agent usage statistics on dashboard', 'dashboard-section'),
  ('dashboard-error-rates', 'Error Rates Card', 'Error monitoring on dashboard', 'dashboard-section'),
  ('dashboard-recent-logins', 'Recent Logins', 'Recent login activity on dashboard', 'dashboard-section'),
  ('dashboard-top-agents', 'Top Active Agents', 'Top performing agents on dashboard', 'dashboard-section'),
  ('agents', 'Agents', 'Agent management and monitoring', 'core'),
  ('users', 'Users', 'User management and profiles', 'core'),
  ('scripts', 'Scripts', 'Script and batch management', 'core'),
  ('scripts-batches', 'Script Batches', 'Batch execution management', 'scripts'),
  ('scripts-settings', 'Script Settings', 'Script configuration settings', 'scripts'),
  ('scripts-templates', 'Script Templates', 'Template management for scripts', 'scripts'),
  ('chat-inbox', 'Chat Inbox', 'Chat conversation management', 'communication'),
  ('team-management', 'Team Management', 'Team and member management', 'admin'),
  ('access-control', 'Access Control', 'Page permissions and role management', 'admin'),
  ('system-settings', 'System Settings', 'System configuration and settings', 'admin'),
  ('system-settings-theme', 'Theme Settings', 'Theme customization in system settings', 'system-section'),
  ('system-settings-ai', 'AI Model Settings', 'AI configuration in system settings', 'system-section'),
  ('system-settings-api', 'API & Rate Limits', 'API configuration in system settings', 'system-section'),
  ('system-settings-security', 'Security Settings', 'Security configuration in system settings', 'system-section'),
  ('system-settings-notifications', 'Notification Settings', 'Notification configuration in system settings', 'system-section'),
  ('profile-settings', 'Profile Settings', 'User profile and account settings', 'user'),
  ('api-keys', 'API Keys', 'API key management', 'admin'),
  ('security', 'Security', 'Security monitoring and policies', 'admin'),
  ('security-dashboard', 'Security Dashboard', 'Security overview and monitoring', 'security'),
  ('security-tests', 'Security Tests', 'Security testing and validation', 'security'),
  ('audit', 'Audit Logs', 'System audit and activity logs', 'admin'),
  ('plans', 'Plans & Billing', 'Subscription and billing management', 'admin'),
  ('widget-management', 'Widget Management', 'Chat widget configuration', 'widgets'),
  ('widget-edit', 'Widget Editor', 'Widget editing and customization', 'widgets'),
  ('widget-test', 'Widget Testing', 'Widget testing and preview', 'widgets'),
  ('widget-deployment', 'Widget Deployment', 'Widget deployment checklist', 'widgets'),
  ('integrations', 'Integrations', 'Third-party integrations', 'admin'),
  ('tasks', 'Tasks', 'Task management and monitoring', 'core'),
  ('command-policies', 'Command Policies', 'Command execution policies', 'security'),
  ('assertion-check', 'Assertion Check', 'System assertion validation', 'admin'),
  ('qa-checklist', 'QA Checklist', 'Quality assurance checklist', 'admin'),
  ('render-templates', 'Render Templates', 'Template rendering demo', 'development')
ON CONFLICT (key) DO UPDATE SET
  label = EXCLUDED.label,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  updated_at = now();

-- Create comprehensive role templates
INSERT INTO console_role_templates (role, page_key, can_view, can_edit, can_delete, description) VALUES
  -- Owner permissions (full access to everything)
  ('Owner', 'dashboard', true, true, true, 'Full dashboard access'),
  ('Owner', 'dashboard-revenue', true, true, true, 'Revenue section access'),
  ('Owner', 'dashboard-ai-costs', true, true, true, 'AI cost monitoring access'),
  ('Owner', 'dashboard-agent-usage', true, true, true, 'Agent usage statistics access'),
  ('Owner', 'dashboard-error-rates', true, true, true, 'Error monitoring access'),
  ('Owner', 'dashboard-recent-logins', true, true, true, 'Recent logins access'),
  ('Owner', 'dashboard-top-agents', true, true, true, 'Top agents access'),
  ('Owner', 'agents', true, true, true, 'Full agent management'),
  ('Owner', 'users', true, true, true, 'Full user management'),
  ('Owner', 'scripts', true, true, true, 'Full script management'),
  ('Owner', 'scripts-batches', true, true, true, 'Full batch management'),
  ('Owner', 'scripts-settings', true, true, true, 'Script settings access'),
  ('Owner', 'scripts-templates', true, true, true, 'Template management'),
  ('Owner', 'chat-inbox', true, true, true, 'Full chat management'),
  ('Owner', 'team-management', true, true, true, 'Full team management'),
  ('Owner', 'access-control', true, true, true, 'Full access control management'),
  ('Owner', 'system-settings', true, true, true, 'Full system settings'),
  ('Owner', 'system-settings-theme', true, true, true, 'Theme customization'),
  ('Owner', 'system-settings-ai', true, true, true, 'AI configuration'),
  ('Owner', 'system-settings-api', true, true, true, 'API configuration'),
  ('Owner', 'system-settings-security', true, true, true, 'Security configuration'),
  ('Owner', 'system-settings-notifications', true, true, true, 'Notification configuration'),
  ('Owner', 'profile-settings', true, true, true, 'Profile management'),
  ('Owner', 'api-keys', true, true, true, 'API key management'),
  ('Owner', 'security', true, true, true, 'Security monitoring'),
  ('Owner', 'security-dashboard', true, true, true, 'Security dashboard'),
  ('Owner', 'security-tests', true, true, true, 'Security testing'),
  ('Owner', 'audit', true, true, true, 'Audit logs access'),
  ('Owner', 'plans', true, true, true, 'Billing management'),
  ('Owner', 'widget-management', true, true, true, 'Widget management'),
  ('Owner', 'widget-edit', true, true, true, 'Widget editing'),
  ('Owner', 'widget-test', true, true, true, 'Widget testing'),
  ('Owner', 'widget-deployment', true, true, true, 'Widget deployment'),
  ('Owner', 'integrations', true, true, true, 'Integration management'),
  ('Owner', 'tasks', true, true, true, 'Task management'),
  ('Owner', 'command-policies', true, true, true, 'Policy management'),
  ('Owner', 'assertion-check', true, true, true, 'Assertion checking'),
  ('Owner', 'qa-checklist', true, true, true, 'QA access'),
  ('Owner', 'render-templates', true, true, true, 'Template rendering'),

  -- Admin permissions (similar to owner but slightly restricted)
  ('Admin', 'dashboard', true, true, false, 'Dashboard access with edit rights'),
  ('Admin', 'dashboard-revenue', true, true, false, 'Revenue section access'),
  ('Admin', 'dashboard-ai-costs', true, true, false, 'AI cost monitoring access'),
  ('Admin', 'dashboard-agent-usage', true, true, false, 'Agent usage statistics access'),
  ('Admin', 'dashboard-error-rates', true, true, false, 'Error monitoring access'),
  ('Admin', 'dashboard-recent-logins', true, true, false, 'Recent logins access'),
  ('Admin', 'dashboard-top-agents', true, true, false, 'Top agents access'),
  ('Admin', 'agents', true, true, true, 'Full agent management'),
  ('Admin', 'users', true, true, true, 'Full user management'),
  ('Admin', 'scripts', true, true, true, 'Full script management'),
  ('Admin', 'scripts-batches', true, true, true, 'Full batch management'),
  ('Admin', 'scripts-settings', true, true, false, 'Script settings access'),
  ('Admin', 'scripts-templates', true, true, true, 'Template management'),
  ('Admin', 'chat-inbox', true, true, true, 'Full chat management'),
  ('Admin', 'team-management', true, true, true, 'Team management'),
  ('Admin', 'access-control', true, true, true, 'Access control management'),
  ('Admin', 'system-settings', true, true, false, 'System settings access'),
  ('Admin', 'system-settings-theme', true, true, false, 'Theme viewing'),
  ('Admin', 'system-settings-ai', true, true, false, 'AI configuration viewing'),
  ('Admin', 'system-settings-api', true, true, false, 'API configuration viewing'),
  ('Admin', 'system-settings-security', true, true, false, 'Security configuration viewing'),
  ('Admin', 'system-settings-notifications', true, true, false, 'Notification configuration viewing'),
  ('Admin', 'profile-settings', true, true, true, 'Profile management'),
  ('Admin', 'api-keys', true, true, true, 'API key management'),
  ('Admin', 'security', true, true, false, 'Security monitoring'),
  ('Admin', 'security-dashboard', true, true, false, 'Security dashboard'),
  ('Admin', 'security-tests', true, true, false, 'Security testing'),
  ('Admin', 'audit', true, false, false, 'Audit logs viewing'),
  ('Admin', 'plans', true, false, false, 'Billing viewing'),
  ('Admin', 'widget-management', true, true, true, 'Widget management'),
  ('Admin', 'widget-edit', true, true, true, 'Widget editing'),
  ('Admin', 'widget-test', true, true, true, 'Widget testing'),
  ('Admin', 'widget-deployment', true, true, true, 'Widget deployment'),
  ('Admin', 'integrations', true, true, false, 'Integration management'),
  ('Admin', 'tasks', true, true, true, 'Task management'),
  ('Admin', 'command-policies', true, true, true, 'Policy management'),
  ('Admin', 'assertion-check', true, false, false, 'Assertion checking'),
  ('Admin', 'qa-checklist', true, true, false, 'QA access'),
  ('Admin', 'render-templates', true, false, false, 'Template rendering'),

  -- Editor permissions (can edit most content but not system settings)
  ('Editor', 'dashboard', true, false, false, 'Dashboard viewing'),
  ('Editor', 'dashboard-revenue', false, false, false, 'No revenue access'),
  ('Editor', 'dashboard-ai-costs', true, false, false, 'AI cost viewing'),
  ('Editor', 'dashboard-agent-usage', true, false, false, 'Agent usage viewing'),
  ('Editor', 'dashboard-error-rates', true, false, false, 'Error monitoring viewing'),
  ('Editor', 'dashboard-recent-logins', false, false, false, 'No login activity access'),
  ('Editor', 'dashboard-top-agents', true, false, false, 'Top agents viewing'),
  ('Editor', 'agents', true, true, false, 'Agent editing'),
  ('Editor', 'users', true, true, false, 'User editing'),
  ('Editor', 'scripts', true, true, false, 'Script editing'),
  ('Editor', 'scripts-batches', true, true, false, 'Batch editing'),
  ('Editor', 'scripts-settings', true, false, false, 'Script settings viewing'),
  ('Editor', 'scripts-templates', true, true, false, 'Template editing'),
  ('Editor', 'chat-inbox', true, true, false, 'Chat management'),
  ('Editor', 'team-management', false, false, false, 'No team management'),
  ('Editor', 'access-control', false, false, false, 'No access control'),
  ('Editor', 'system-settings', false, false, false, 'No system settings'),
  ('Editor', 'profile-settings', true, true, false, 'Profile editing'),
  ('Editor', 'api-keys', false, false, false, 'No API key access'),
  ('Editor', 'security', false, false, false, 'No security access'),
  ('Editor', 'audit', false, false, false, 'No audit access'),
  ('Editor', 'plans', false, false, false, 'No billing access'),
  ('Editor', 'widget-management', true, true, false, 'Widget editing'),
  ('Editor', 'widget-edit', true, true, false, 'Widget editing'),
  ('Editor', 'widget-test', true, true, false, 'Widget testing'),
  ('Editor', 'widget-deployment', true, false, false, 'Widget deployment viewing'),
  ('Editor', 'integrations', false, false, false, 'No integration access'),
  ('Editor', 'tasks', true, true, false, 'Task editing'),
  ('Editor', 'command-policies', true, false, false, 'Policy viewing'),
  ('Editor', 'assertion-check', false, false, false, 'No assertion access'),
  ('Editor', 'qa-checklist', true, false, false, 'QA viewing'),
  ('Editor', 'render-templates', true, false, false, 'Template viewing'),

  -- Viewer permissions (read-only access to most content)
  ('Viewer', 'dashboard', true, false, false, 'Dashboard viewing'),
  ('Viewer', 'dashboard-revenue', false, false, false, 'No revenue access'),
  ('Viewer', 'dashboard-ai-costs', false, false, false, 'No cost access'),
  ('Viewer', 'dashboard-agent-usage', true, false, false, 'Agent usage viewing'),
  ('Viewer', 'dashboard-error-rates', true, false, false, 'Error monitoring viewing'),
  ('Viewer', 'dashboard-recent-logins', false, false, false, 'No login activity access'),
  ('Viewer', 'dashboard-top-agents', true, false, false, 'Top agents viewing'),
  ('Viewer', 'agents', true, false, false, 'Agent viewing'),
  ('Viewer', 'users', true, false, false, 'User viewing'),
  ('Viewer', 'scripts', true, false, false, 'Script viewing'),
  ('Viewer', 'scripts-batches', true, false, false, 'Batch viewing'),
  ('Viewer', 'scripts-settings', false, false, false, 'No script settings'),
  ('Viewer', 'scripts-templates', true, false, false, 'Template viewing'),
  ('Viewer', 'chat-inbox', true, false, false, 'Chat viewing'),
  ('Viewer', 'team-management', false, false, false, 'No team management'),
  ('Viewer', 'access-control', false, false, false, 'No access control'),
  ('Viewer', 'system-settings', false, false, false, 'No system settings'),
  ('Viewer', 'profile-settings', true, true, false, 'Profile editing'),
  ('Viewer', 'api-keys', false, false, false, 'No API key access'),
  ('Viewer', 'security', false, false, false, 'No security access'),
  ('Viewer', 'audit', false, false, false, 'No audit access'),
  ('Viewer', 'plans', false, false, false, 'No billing access'),
  ('Viewer', 'widget-management', true, false, false, 'Widget viewing'),
  ('Viewer', 'widget-edit', false, false, false, 'No widget editing'),
  ('Viewer', 'widget-test', true, false, false, 'Widget testing'),
  ('Viewer', 'widget-deployment', false, false, false, 'No deployment access'),
  ('Viewer', 'integrations', false, false, false, 'No integration access'),
  ('Viewer', 'tasks', true, false, false, 'Task viewing'),
  ('Viewer', 'command-policies', true, false, false, 'Policy viewing'),
  ('Viewer', 'assertion-check', false, false, false, 'No assertion access'),
  ('Viewer', 'qa-checklist', true, false, false, 'QA viewing'),
  ('Viewer', 'render-templates', true, false, false, 'Template viewing')
ON CONFLICT (role, page_key) DO UPDATE SET
  can_view = EXCLUDED.can_view,
  can_edit = EXCLUDED.can_edit,
  can_delete = EXCLUDED.can_delete,
  description = EXCLUDED.description,
  updated_at = now();

-- Remove any duplicate role templates
DELETE FROM console_role_templates a USING (
  SELECT MIN(ctid) as ctid, role, page_key
  FROM console_role_templates 
  GROUP BY role, page_key HAVING COUNT(*) > 1
) b
WHERE a.role = b.role AND a.page_key = b.page_key AND a.ctid <> b.ctid;