-- Add missing columns to console_pages table
ALTER TABLE console_pages 
ADD COLUMN IF NOT EXISTS category text DEFAULT 'core',
ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now();

-- Create comprehensive page list
INSERT INTO console_pages (key, label, category) VALUES
  ('dashboard', 'Dashboard', 'core'),
  ('dashboard-revenue', 'Revenue Section', 'dashboard-section'),
  ('dashboard-ai-costs', 'AI Cost Monitor', 'dashboard-section'),
  ('dashboard-agent-usage', 'Agent Usage Chart', 'dashboard-section'),
  ('dashboard-error-rates', 'Error Rates Card', 'dashboard-section'),
  ('dashboard-recent-logins', 'Recent Logins', 'dashboard-section'),
  ('dashboard-top-agents', 'Top Active Agents', 'dashboard-section'),
  ('agents', 'Agents', 'core'),
  ('users', 'Users', 'core'),
  ('scripts', 'Scripts', 'core'),
  ('scripts-batches', 'Script Batches', 'scripts'),
  ('scripts-settings', 'Script Settings', 'scripts'),
  ('scripts-templates', 'Script Templates', 'scripts'),
  ('chat-inbox', 'Chat Inbox', 'communication'),
  ('team-management', 'Team Management', 'admin'),
  ('access-control', 'Access Control', 'admin'),
  ('system-settings', 'System Settings', 'admin'),
  ('system-settings-theme', 'Theme Settings', 'system-section'),
  ('system-settings-ai', 'AI Model Settings', 'system-section'),
  ('system-settings-api', 'API & Rate Limits', 'system-section'),
  ('system-settings-security', 'Security Settings', 'system-section'),
  ('system-settings-notifications', 'Notification Settings', 'system-section'),
  ('profile-settings', 'Profile Settings', 'user'),
  ('api-keys', 'API Keys', 'admin'),
  ('security', 'Security', 'admin'),
  ('security-dashboard', 'Security Dashboard', 'security'),
  ('security-tests', 'Security Tests', 'security'),
  ('audit', 'Audit Logs', 'admin'),
  ('plans', 'Plans & Billing', 'admin'),
  ('widget-management', 'Widget Management', 'widgets'),
  ('widget-edit', 'Widget Editor', 'widgets'),
  ('widget-test', 'Widget Testing', 'widgets'),
  ('widget-deployment', 'Widget Deployment', 'widgets'),
  ('integrations', 'Integrations', 'admin'),
  ('tasks', 'Tasks', 'core'),
  ('command-policies', 'Command Policies', 'security'),
  ('assertion-check', 'Assertion Check', 'admin'),
  ('qa-checklist', 'QA Checklist', 'admin'),
  ('render-templates', 'Render Templates', 'development')
ON CONFLICT (key) DO UPDATE SET
  label = EXCLUDED.label,
  category = EXCLUDED.category,
  updated_at = now();

-- Create comprehensive role templates
INSERT INTO console_role_templates (role, page_key, can_view, can_edit, can_delete) VALUES
  -- Owner permissions (full access to everything)
  ('Owner', 'dashboard', true, true, true),
  ('Owner', 'dashboard-revenue', true, true, true),
  ('Owner', 'dashboard-ai-costs', true, true, true),
  ('Owner', 'dashboard-agent-usage', true, true, true),
  ('Owner', 'dashboard-error-rates', true, true, true),
  ('Owner', 'dashboard-recent-logins', true, true, true),
  ('Owner', 'dashboard-top-agents', true, true, true),
  ('Owner', 'agents', true, true, true),
  ('Owner', 'users', true, true, true),
  ('Owner', 'scripts', true, true, true),
  ('Owner', 'scripts-batches', true, true, true),
  ('Owner', 'scripts-settings', true, true, true),
  ('Owner', 'scripts-templates', true, true, true),
  ('Owner', 'chat-inbox', true, true, true),
  ('Owner', 'team-management', true, true, true),
  ('Owner', 'access-control', true, true, true),
  ('Owner', 'system-settings', true, true, true),
  ('Owner', 'system-settings-theme', true, true, true),
  ('Owner', 'system-settings-ai', true, true, true),
  ('Owner', 'system-settings-api', true, true, true),
  ('Owner', 'system-settings-security', true, true, true),
  ('Owner', 'system-settings-notifications', true, true, true),
  ('Owner', 'profile-settings', true, true, true),
  ('Owner', 'api-keys', true, true, true),
  ('Owner', 'security', true, true, true),
  ('Owner', 'security-dashboard', true, true, true),
  ('Owner', 'security-tests', true, true, true),
  ('Owner', 'audit', true, true, true),
  ('Owner', 'plans', true, true, true),
  ('Owner', 'widget-management', true, true, true),
  ('Owner', 'widget-edit', true, true, true),
  ('Owner', 'widget-test', true, true, true),
  ('Owner', 'widget-deployment', true, true, true),
  ('Owner', 'integrations', true, true, true),
  ('Owner', 'tasks', true, true, true),
  ('Owner', 'command-policies', true, true, true),
  ('Owner', 'assertion-check', true, true, true),
  ('Owner', 'qa-checklist', true, true, true),
  ('Owner', 'render-templates', true, true, true),

  -- Admin permissions (similar to owner but slightly restricted)
  ('Admin', 'dashboard', true, true, false),
  ('Admin', 'dashboard-revenue', true, true, false),
  ('Admin', 'dashboard-ai-costs', true, true, false),
  ('Admin', 'dashboard-agent-usage', true, true, false),
  ('Admin', 'dashboard-error-rates', true, true, false),
  ('Admin', 'dashboard-recent-logins', true, true, false),
  ('Admin', 'dashboard-top-agents', true, true, false),
  ('Admin', 'agents', true, true, true),
  ('Admin', 'users', true, true, true),
  ('Admin', 'scripts', true, true, true),
  ('Admin', 'scripts-batches', true, true, true),
  ('Admin', 'scripts-settings', true, true, false),
  ('Admin', 'scripts-templates', true, true, true),
  ('Admin', 'chat-inbox', true, true, true),
  ('Admin', 'team-management', true, true, true),
  ('Admin', 'access-control', true, true, true),
  ('Admin', 'system-settings', true, true, false),
  ('Admin', 'system-settings-theme', true, true, false),
  ('Admin', 'system-settings-ai', true, true, false),
  ('Admin', 'system-settings-api', true, true, false),
  ('Admin', 'system-settings-security', true, true, false),
  ('Admin', 'system-settings-notifications', true, true, false),
  ('Admin', 'profile-settings', true, true, true),
  ('Admin', 'api-keys', true, true, true),
  ('Admin', 'security', true, true, false),
  ('Admin', 'security-dashboard', true, true, false),
  ('Admin', 'security-tests', true, true, false),
  ('Admin', 'audit', true, false, false),
  ('Admin', 'plans', true, false, false),
  ('Admin', 'widget-management', true, true, true),
  ('Admin', 'widget-edit', true, true, true),
  ('Admin', 'widget-test', true, true, true),
  ('Admin', 'widget-deployment', true, true, true),
  ('Admin', 'integrations', true, true, false),
  ('Admin', 'tasks', true, true, true),
  ('Admin', 'command-policies', true, true, true),
  ('Admin', 'assertion-check', true, false, false),
  ('Admin', 'qa-checklist', true, true, false),
  ('Admin', 'render-templates', true, false, false),

  -- Editor permissions (can edit most content but not system settings)
  ('Editor', 'dashboard', true, false, false),
  ('Editor', 'dashboard-revenue', false, false, false),
  ('Editor', 'dashboard-ai-costs', true, false, false),
  ('Editor', 'dashboard-agent-usage', true, false, false),
  ('Editor', 'dashboard-error-rates', true, false, false),
  ('Editor', 'dashboard-recent-logins', false, false, false),
  ('Editor', 'dashboard-top-agents', true, false, false),
  ('Editor', 'agents', true, true, false),
  ('Editor', 'users', true, true, false),
  ('Editor', 'scripts', true, true, false),
  ('Editor', 'scripts-batches', true, true, false),
  ('Editor', 'scripts-settings', true, false, false),
  ('Editor', 'scripts-templates', true, true, false),
  ('Editor', 'chat-inbox', true, true, false),
  ('Editor', 'team-management', false, false, false),
  ('Editor', 'access-control', false, false, false),
  ('Editor', 'system-settings', false, false, false),
  ('Editor', 'profile-settings', true, true, false),
  ('Editor', 'api-keys', false, false, false),
  ('Editor', 'security', false, false, false),
  ('Editor', 'audit', false, false, false),
  ('Editor', 'plans', false, false, false),
  ('Editor', 'widget-management', true, true, false),
  ('Editor', 'widget-edit', true, true, false),
  ('Editor', 'widget-test', true, true, false),
  ('Editor', 'widget-deployment', true, false, false),
  ('Editor', 'integrations', false, false, false),
  ('Editor', 'tasks', true, true, false),
  ('Editor', 'command-policies', true, false, false),
  ('Editor', 'assertion-check', false, false, false),
  ('Editor', 'qa-checklist', true, false, false),
  ('Editor', 'render-templates', true, false, false),

  -- Viewer permissions (read-only access to most content)
  ('Viewer', 'dashboard', true, false, false),
  ('Viewer', 'dashboard-revenue', false, false, false),
  ('Viewer', 'dashboard-ai-costs', false, false, false),
  ('Viewer', 'dashboard-agent-usage', true, false, false),
  ('Viewer', 'dashboard-error-rates', true, false, false),
  ('Viewer', 'dashboard-recent-logins', false, false, false),
  ('Viewer', 'dashboard-top-agents', true, false, false),
  ('Viewer', 'agents', true, false, false),
  ('Viewer', 'users', true, false, false),
  ('Viewer', 'scripts', true, false, false),
  ('Viewer', 'scripts-batches', true, false, false),
  ('Viewer', 'scripts-settings', false, false, false),
  ('Viewer', 'scripts-templates', true, false, false),
  ('Viewer', 'chat-inbox', true, false, false),
  ('Viewer', 'team-management', false, false, false),
  ('Viewer', 'access-control', false, false, false),
  ('Viewer', 'system-settings', false, false, false),
  ('Viewer', 'profile-settings', true, true, false),
  ('Viewer', 'api-keys', false, false, false),
  ('Viewer', 'security', false, false, false),
  ('Viewer', 'audit', false, false, false),
  ('Viewer', 'plans', false, false, false),
  ('Viewer', 'widget-management', true, false, false),
  ('Viewer', 'widget-edit', false, false, false),
  ('Viewer', 'widget-test', true, false, false),
  ('Viewer', 'widget-deployment', false, false, false),
  ('Viewer', 'integrations', false, false, false),
  ('Viewer', 'tasks', true, false, false),
  ('Viewer', 'command-policies', true, false, false),
  ('Viewer', 'assertion-check', false, false, false),
  ('Viewer', 'qa-checklist', true, false, false),
  ('Viewer', 'render-templates', true, false, false)
ON CONFLICT (role, page_key) DO UPDATE SET
  can_view = EXCLUDED.can_view,
  can_edit = EXCLUDED.can_edit,
  can_delete = EXCLUDED.can_delete,
  updated_at = now();

-- Remove any duplicate role templates
DELETE FROM console_role_templates a USING (
  SELECT MIN(ctid) as ctid, role, page_key
  FROM console_role_templates 
  GROUP BY role, page_key HAVING COUNT(*) > 1
) b
WHERE a.role = b.role AND a.page_key = b.page_key AND a.ctid <> b.ctid;