// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Debug the URLs being used
console.log('🔧 Supabase Client Debug:', {
  VITE_SUPABASE_URL: import.meta.env.VITE_SUPABASE_URL,
  SUPABASE_URL,
  ENV_LOADED: true
});

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  },
  global: {
    headers: {
      'x-client-info': 'supabase-js-web',
    },
      fetch: (url, options = {}) => {
        // Adaptive timeout based on request type and detected latency
        let timeout = 30000; // Default 30s
        
        if (url.includes('/functions/')) {
          // Edge functions get longer timeout (90s for high-latency regions)
          timeout = 90000;
        } else if (url.includes('/auth/v1/token')) {
          // Auth operations get extended timeout for regional issues
          timeout = 45000;
        }
        
        return fetch(url, {
          ...options,
          signal: AbortSignal.timeout(timeout),
        }).catch(error => {
          console.error('Supabase fetch error:', error);
          if (error.name === 'TimeoutError' || error.name === 'AbortError') {
            throw new Error(`Request timed out after ${timeout/1000} seconds. This may be due to network conditions in your region. Please try again.`);
          }
          if (error.message?.includes('Failed to fetch') || error.message?.includes('NetworkError')) {
            throw new Error('Network connection failed. This may be due to regional connectivity issues. Please check your internet connection and try again.');
          }
          throw error;
        });
      },
  },
  db: {
    schema: 'public',
  },
  realtime: {
    params: {
      eventsPerSecond: 10,
    },
  },
});